# Generated by Django 2.2 on 2021-10-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Descripción de la Categoría', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('compuesto_activo', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='inv/fotos')),
                ('gramaje', models.CharField(max_length=100)),
                ('caducidad', models.DateField()),
                ('lote', models.CharField(blank=True, max_length=200)),
                ('codigo_barra', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('descuento', models.FloatField(default=0)),
                ('precio_descuento', models.FloatField(default=0, editable=False)),
                ('precio_compra', models.FloatField(default=0)),
                ('precio_venta', models.FloatField(default=0)),
                ('stock_inicial', models.IntegerField(default=0)),
                ('stock_final', models.IntegerField(default=0)),
                ('ganancia', models.FloatField(blank=True, default=0, editable=False)),
                ('generico', models.BooleanField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'unique_together': {('nombre', 'codigo_barra')},
            },
        ),
    ]
