# Generated by Django 2.2 on 2021-10-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='compuesto_activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='generico',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='gramaje',
        ),
        migrations.AlterField(
            model_name='producto',
            name='caducidad',
            field=models.DateField(blank=True),
        ),
    ]
