# Generated by Django 2.2 on 2021-11-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20211015_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
