# Generated by Django 2.2 on 2021-10-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20211015_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=50),
        ),
    ]
