# Generated by Django 2.2 on 2021-10-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20211019_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
