# Generated by Django 2.2 on 2021-10-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20211019_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=50),
        ),
    ]
