# Generated by Django 2.2 on 2021-10-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20211019_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
