# Generated by Django 2.2 on 2021-10-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20211019_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='contador',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=50, null=True),
        ),
    ]
