# Generated by Django 2.2 on 2021-10-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_abono_contador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='contador',
        ),
    ]
