# Generated by Django 2.2 on 2021-10-12 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCorte', models.DateTimeField(verbose_name='Fecha de corte')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('efectivo', models.FloatField(default=0)),
                ('total_efectivo', models.FloatField(default=0, editable=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
