# Generated by Django 2.2 on 2021-10-12 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_total', models.BigIntegerField(default=0, editable=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA', 'TARJETA'), ('MIXTO', 'MIXTO')], default='EFECTIVO', max_length=100, verbose_name='METODO')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.FloatField(default=0, editable=False)),
                ('subtotal_descuento', models.FloatField(default=0, editable=False)),
                ('descuento', models.FloatField(default=0, editable=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=50)),
                ('total_efectivo', models.FloatField(default=0, editable=False)),
                ('total_tarjeta', models.FloatField(default=0, editable=False)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ventas Generales',
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('venta', models.FloatField(default=0, editable=False)),
                ('importe', models.FloatField(default=0, editable=False)),
                ('descuento', models.FloatField(default=0, editable=False)),
                ('importe_descuento', models.FloatField(default=0, editable=False)),
                ('ga', models.FloatField(blank=True, default=0, editable=False)),
                ('num_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.VentaGeneral')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_nombre', to='inv.Producto')),
            ],
        ),
    ]
