# Generated by Django 2.2 on 2021-10-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20211015_1341'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventageneral',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_nombre', to='cliente.Cliente'),
        ),
        migrations.AddField(
            model_name='ventageneral',
            name='resto',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ventageneral',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
