# Generated by Django 2.2 on 2021-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20211016_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventageneral',
            name='status',
            field=models.BooleanField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADO', 'PAGADO')], null=True),
        ),
    ]
