# Generated by Django 2.2 on 2021-10-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20211015_1341'),
        ('venta', '0003_auto_20211019_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventageneral',
            name='abonos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abono_importe', to='cliente.Abono'),
        ),
    ]
