# Generated by Django 2.2 on 2021-10-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_remove_ventageneral_abonos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventageneral',
            name='resto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
    ]
