# Generated by Django 2.2 on 2021-10-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20211019_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventageneral',
            name='contador',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='ventageneral',
            name='resto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=50, null=True),
        ),
    ]
