# Generated by Django 2.2 on 2021-10-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_auto_20211019_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventageneral',
            name='contador',
        ),
    ]
