# Generated by Django 2.2 on 2021-10-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_remove_ventageneral_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventageneral',
            name='abon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=50, null=True),
        ),
    ]
