# Generated by Django 2.2 on 2021-10-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_ventageneral_abon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventageneral',
            name='abon',
        ),
    ]
