# Generated by Django 2.2 on 2021-10-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_remove_ventageneral_abon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventageneral',
            name='resto_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=50, null=True),
        ),
    ]
