# Generated by Django 2.2 on 2021-10-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_ventageneral_resto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventageneral',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
