# Generated by Django 2.2 on 2021-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_auto_20211019_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventageneral',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
